config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects
  get 'download_input', to: 'testcases#download_input'
  get 'download_output', to: 'testcases#download_output'
  post '/download-attachments', to: "projects#process_and_create_zip_file", as: 'download_documents'
  post 'generate_output', to: 'projects#generate_output'
  get 'add_code', to: 'projects#add_code'
  get 'online_ide', to: 'projects#online_ide'
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :testcases, dependent: :destroy
  has_many :tests, dependent: :destroy
  validates :name ,presence: true, length: {minimum: 6,maximum: 100}
  validates :testcaseCount, numericality: { only_integer: true ,greater_than: 0, less_than_or_equal_to: 10}
  accepts_nested_attributes_for :tests
end

app/controllers/projects_controller.rb
require 'zip'
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
  end
  def index
    @projects =  current_user.projects
  end
  def new
    @project = Project.new
  end
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    a = @project.tests.destroy_all
    if @project.save
        errors = 0
        for i in 1..@project.testcaseCount
              inputFileName = "in" + i.to_s + ".txt"
              fileobject = File.new(inputFileName,"w+");
              input = ""
              errors = 0
              a.each_with_index do |test,index|
                  if test.name.blank?
                    test.destroy
                    next
                  end
                  test.project_id = @project.id
                  if !test.valid?
                    @project.errors[:base] << "In Input Line => " + (index+1).to_s + ": " + "#{test.errors.full_messages.join(". ")}."
                    errors = 1
                    break
                  elsif test.name == "int"
                    input += generate_integer(test.lowlimit, test.highlimit) + " "
                  elsif test.name == "intarray"
                    input += generate_integer_1d_array(test.rowsize,test.lowlimit,test.highlimit)
                  elsif test.name == "int2darray"
                    input += generate_integer_2d_array(test.rowsize,test.colsize,test.lowlimit,test.highlimit)
                  elsif test.name == "string"
                    input += generate_string(test.rowsize,test.rowsize,test.flag) + " "
                  elsif test.name == "stringarray"
                    input += generate_string_array(test.rowsize,test.lowlimit,test.highlimit,test.flag)
                  end
                  test.save
                  @project.tests << test
              end
            if errors == 1
              break
            end
            fileobject.syswrite(input);
            @test = Testcase.new(testfile: fileobject)
            @project.testcases << @test
        end
        if errors == 1 || @project.tests.count == 0
          #Test.where(project_id: @project.id).destroy_all
          if @project.tests.count == 0
                @project.errors[:base] << "Atleast one line of input is necessary"
          end
          @project.tests.destroy_all
          @project.destroy
          render 'new'
          return
        end
      flash[:notice] = "Project was created successfully."
      redirect_to project_path(@project)
        return
    else
      @project.destroy
      render 'new'
      return
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    #generate testcases again
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:notice] = "Project was updated successfully"
      redirect_to project_path(@project)
    else
     render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end

  #download all testcases in a zip
  def process_and_create_zip_file
    @project = Project.find(params[:format].to_i)
    compressed_filestream = Zip::OutputStream.write_buffer do |zos|
      @project.testcases.each do |p|
        zos.put_next_entry p.testfile_file_name
        zos.print(Paperclip.io_adapters.for(p.testfile).read)


        zos.put_next_entry p.output_file_name
        zos.print(Paperclip.io_adapters.for(p.output).read)

      end
    end
    compressed_filestream.rewind
    send_data compressed_filestream.read, filename: "testcases.zip"
  end


  def generate_output
    @project = Project.find(params[:format].to_i)
    if @project.code.blank?
      flash[:error] = "Add code to your project first"
    else
        url = URI("https://api.jdoodle.com/v1/execute")
        http = Net::HTTP.new(url.host, url.port)
        http.use_ssl = true
        request = Net::HTTP::Post.new(url.path)
        request["Content-Type"] = 'application/json'
        @project.testcases.each_with_index do |testcase, index|
          #input = testcase.testfile.copy_to_local_file.read.to_s
          input = Paperclip.io_adapters.for(testcase.testfile).read
          input = input.to_s
          request.body = {
              "script" => @project.code,
              "language" => "cpp14",
              "versionIndex" => "3",
              "clientId" => Rails.application.credentials.jdoodle[:clientId],
              "clientSecret" => Rails.application.credentials.jdoodle[:clientSecret],
              "stdin" => input}.to_json
              response = http.request(request)
              obj = JSON.parse(response.read_body)
              output = obj["output"].to_s
              output = " " + output
              outputFileName = "out" + (index+1).to_s  + ".txt"
              fileobject = File.new(outputFileName,"w+");
              fileobject.syswrite(output);
              testcase.output = fileobject
              testcase.save
        end
    end
    render 'show'
  end
    def add_code
      @project = Project.find(params[:format].to_i)
    end
    def online_ide

    end

  private
  def project_params
    params.require(:project).permit(:name, :testcaseCount, :code, tests_attributes: [:id ,:name, :lowlimit, :highlimit, :rowsize, :colsize, :flag])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_displayAll.html.erb
<table class="table table-bordered table-striped mb-0 text-center">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">TestCase-Count</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @projects.each do |project| %>
    <tr>
    <td><%= project.id %></td>
    <td><%= project.name %></td>
    <td><%= project.testcaseCount %></td>
    <td><%= link_to 'Show',project_path(project),:class => "badge badge-dark" %>&nbsp;
        <%= link_to 'Edit',edit_project_path(project),:class => "badge badge-dark" %>&nbsp;
        <%= link_to 'Delete',project_path(project),:class => "badge badge-dark" ,method: :delete %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/projects/_form.html.erb
<div class="container">

<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors',obj: @project %>
    <%= form_with(model: @project,class: "shadow p-3 mb-5 bg-dark rounded",local: true) do |f| %>
    <div class="form-group row">
      <%= f.label :name,class: "col-2 col-form-label text-light" %>
      <div class="col-10">
        <%= f.text_field :name,class: "form-control shadow rounded",placeholder: "Name of project" %>
      </div>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.submit class: "btn btn-outline-light btn-lg" %>
    </div>
  <% end %>
</div>
<div class="mb-3">
  <%= link_to '[Cancel and return to home page ]', projects_path,class: "text-info" %>
</div>
</div>
</div>

app/views/projects/add_code.html.erb
<div class = "container mt-4">
    <script>
        SEC_HTTPS = true;
        SEC_BASE = "compilers.widgets.sphere-engine.com";
        (function(d, s, id){ SEC = window.SEC || (window.SEC = []);
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return; js = d.createElement(s); js.id = id;
        js.src = (SEC_HTTPS ? "https" : "http") + "://" + SEC_BASE + "/static/sdk/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
        }(document, "script", "sphere-engine-compilers-jssdk"));
        SEC.ready=function(e){"loading"!=document.readyState&&"interactive"!=document.readyState?e():window.addEventListener("load",e)};
    </script>
</div>
<div class="sec-widget" data-widget="2adbe0da9448563569f4c6416339b355"></div>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <%= form_with(model: @project,url: project_path(@project), method: :patch, class: "p-3 mb-5 bg-white rounded",local: true) do |f| %>
    <div class="form-group row">
         <%= f.text_area :code, rows: 10,class: "form-control  rounded",placeholder: "                                                                               After successfully compiling the code from above editor paste the code here and save." %>
    </div>
    <div class="form-group row justify-content-center">
         <%= f.submit "Save Code", class: "btn btn-outline-dark btn-lg" %>
    </div>
  <% end %>
</div>

app/views/projects/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<div class = "container"><h2 class = "mt-4">Your Projects</h2>
<%= render 'displayAll' %>
<br />
<%= link_to 'New Project',new_project_path,:class => "btn btn-dark" %>
</div>

app/views/projects/new.html.erb
<h1 class="text-center mt-4 strong">Create a new Project</h1>
<div class="container">

<div class="row justify-content-center">
  <div class="col-10">
    <%= render 'shared/errors',obj: @project %>
    <%= form_with(model: @project,class: "shadow p-3 mb-5 bg-dark rounded",local: true) do |f| %>
    <div class="form-group row">
      <%= f.label :name,class: "col-2 col-form-label text-light" %>
      <div class="col-10">
        <%= f.text_field :name,class: "form-control shadow rounded",placeholder: "Name of project" %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :testcase_Count,class: "col-2 col-form-label text-light" %>
      <div class="col-10">
        <%= f.number_field :testcaseCount,class: "form-control shadow rounded",placeholder: "Enter the number of testcases you want" %>
      </div>
    </div>

    <br>

    <div class = "form-group h1 text-light text-center">
        Testcase Description
    </div>

    <br>

    <div class = "form-group row">
    <label class = "col-3 col-form-label text-light">Number of line of testcases</label>
    <input type = "text" placeholder = "Enter number of lines of input" id = "testlines" class = "form-control shadow rounded col-4" />
    <button type = "button" onclick = "displaylines()" class = "btn btn-outline-light btn-lg" style = "margin-left: 200px; height: 39px;">Create Test Lines</button>
    </div>
    <div class = "container">
    <div class="form-group text-light">
    <% for i in 1..10 %>
             <div class = "d-none" id = "parentdiv<%= i.to_s %>">
             <br><br>
            Line <%= i.to_s %>:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= f.fields_for :tests, Test.new do |ff| %>
                    <%= ff.radio_button :name, 'int' , id: "int#{i}" %>                 Integer &nbsp;
                    <%= ff.radio_button :name, 'intarray', id: "intarray#{i}" %>        1D Integer Array &nbsp;
                    <%= ff.radio_button :name, 'int2darray', id: "int2darray#{i}" %>    2D Integer Array &nbsp;
                    <%= ff.radio_button :name, 'string', id: "string#{i}" %>            String &nbsp;
                    <%= ff.radio_button :name, 'stringarray', id: "stringarray#{i}" %>  String Array
                    <br>

                <div id = "rangeinput<%= i.to_s %>", class = "d-none">
                            <%= ff.label :Lower_Limit,class: "col-form-label text-light" %>
                        <div class="col-5">
                            <%= ff.number_field :lowlimit,class: "form-control shadow rounded",placeholder: "Enter the lower limit" %>
                        </div>

                            <%= ff.label :Higher_Limit,class: "col-form-label text-light" %>
                        <div class="col-5">
                            <%= ff.number_field :highlimit,class: "form-control shadow rounded",placeholder: "Enter the upper limit" %>
                        </div>

                </div>

                <div id = "rowsizeinput<%= i.to_s %>", class = "d-none">
                            <%= ff.label :Size,class: "col-form-label text-light" %>
                        <div class="col-5">
                            <%= ff.number_field :rowsize,class: "form-control shadow rounded",placeholder: "Enter the size" %>
                        </div>

                </div>

                <div id = "colsizeinput<%= i.to_s %>", class = "d-none">

                            <%= ff.label :Number_of_Columns,class: "col-form-label text-light" %>
                        <div class="col-5">
                            <%= ff.number_field :colsize,class: "form-control shadow rounded",placeholder: "Enter the number of columns" %>
                        </div>

                </div>

                <div id = "flaginput<%= i.to_s %>", class = "d-none">
                            <%= ff.label :Flag,class: "col-form-label text-light" %>
                        <div class="col-5">
                            <%= ff.number_field :flag,class: "form-control shadow rounded",placeholder: "See documentation" %>
                        </div>

                </div>

            <% end %>
            </div>
            <% end %>
    </div>
    </div>
    <br><br>
    <div class="form-group row justify-content-center">
      <%= f.submit class: "btn btn-outline-light btn-lg" %>
    </div>
  <% end %>
</div>
<div class="mb-3">
  <%= link_to '[Cancel and return to home page ]', projects_path,class: "text-info" %>
</div>
</div>
</div>
<script>

    for(let i=1;i<=10;i++){
        document.getElementById("int" + i.toString()).addEventListener("click",function() { console.log(i);displaysubdiv(["rangeinput"],i)},false);
        document.getElementById("intarray" + i.toString()).addEventListener("click",function() {displaysubdiv(["rowsizeinput","rangeinput"],i)},false);
        document.getElementById("int2darray" + i.toString()).addEventListener("click",function() { displaysubdiv(["rowsizeinput","colsizeinput","rangeinput"],i)},false);
        document.getElementById("string" + i.toString()).addEventListener("click",function() { displaysubdiv(["rowsizeinput","flaginput"],i)},false);
        document.getElementById("stringarray" + i.toString()).addEventListener("click",function() { displaysubdiv(["rowsizeinput","rangeinput","flaginput"],i)},false);

    }

    function displaysubdiv(toshow,index){
        console.log(index);
        index = index.toString();
        alldivs = ["rangeinput","rowsizeinput","colsizeinput","flaginput"];
        for(let i = 0;i<alldivs.length;i++){
            hidediv(alldivs[i] + index);

        }

        for(let i = 0;i<toshow.length;i++){
            displaydiv(toshow[i] + index);

        }
    }
    function displaylines()
    {
        let lines = document.getElementById("testlines").value;
        if(lines==""){
            lines = "0";
        }
        lines = parseInt(lines);
        for(let i = 1;i<=lines;i++){
            displaydiv("parentdiv" + i.toString())
        }
    }
    function displaydiv(div_id)
    {
        console.log(div_id)
        document.getElementById(div_id).classList.remove("d-none");
    }
    function hidediv(div_id)
    {
        console.log("hide"  + " " + div_id);
        document.getElementById(div_id).classList.add("d-none");
    }
</script>

app/views/projects/online_ide.html.erb
<div class = "container mt-4">
<script>
        SEC_HTTPS = true;
        SEC_BASE = "compilers.widgets.sphere-engine.com";
        (function(d, s, id){ SEC = window.SEC || (window.SEC = []);
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return; js = d.createElement(s); js.id = id;
        js.src = (SEC_HTTPS ? "https" : "http") + "://" + SEC_BASE + "/static/sdk/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
        }(document, "script", "sphere-engine-compilers-jssdk"));
        SEC.ready=function(e){"loading"!=document.readyState&&"interactive"!=document.readyState?e():window.addEventListener("load",e)};
    </script>

  <div class="sec-widget mt-4" data-widget=Rails.application.credentials.jdoodle[:widget] data-theme="dark"></div>
  </div>

app/views/projects/show.html.erb
<div class = "container">
<h2 class="text-center mt-4"><%= @project.name %></h2>
<div class="table-wrapper-scroll-y my-custom-scrollbar">
<table class="table table-bordered table-striped mb-0 text-center">
  <thead class="thead-light">
    <tr>
      <th scope="col">Testcase Number:</th>
      <th scope="col">Input Link</th>
      <% if  @project.testcases.count>0 && @project.testcases.first.output.exists? %>
        <th scope="col">Output Link</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
  <% @project.testcases.each_with_index do |test, index| %>
    <tr>
    <td><%= index + 1 %></td>
    <td><%= link_to "Download", download_input_path(test), :class => "btn btn-dark" %></td>
    <% if @project.testcases.count>0 && @project.testcases.first.output.exists? %>
     <td><%= link_to "Download", download_output_path(test), :class => "btn btn-dark" %></td></td>
    <% end %>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<%= link_to 'Download All', download_documents_path(@project), method: :post, :class => "btn btn-dark text-center" %>
&nbsp;
<%= link_to @project.code.blank? ? 'Add Code' : 'Edit Code', add_code_path(@project), :class => "btn btn-dark text-center" %>
&nbsp;
  <%= link_to  @project.testcases.count>0 && @project.testcases.first.output.exists? ? 'Generate Outputs Again' : 'Generate Outputs', generate_output_path(@project), method: :post, :class => "btn btn-dark text-center" %>
</div>