config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects
  get 'download_input', to: 'testcases#download_input'
  get 'download_output', to: 'testcases#download_output'
  post '/download-attachments', to: "projects#process_and_create_zip_file", as: 'download_documents'
  post 'generate_output', to: 'projects#generate_output'
  get 'add_code', to: 'projects#add_code'
  get 'online_ide', to: 'projects#online_ide'
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
   <div class="container text-center">
     <small>Copyright &copy; Rishabh Kejariwal, &copy; Tanmay Agrawal, &copy; Abhishek Srivastava</small>
   </div>
 </footer>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">
<%= link_to "Test Overflow", projects_path,:class => "navbar-brand nav-link" %>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
  <!--
  <li class="nav-item active">
    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
  </li>-->
  <% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to 'My Projects',projects_path(current_user),:class => "nav-link" %>
  </li>
  <% end %>
  <% if user_signed_in? %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= current_user.name %>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= link_to 'Edit Profile',edit_user_registration_path,:class => "dropdown-item" %>
      <%= link_to 'Delete Profile', registration_path(current_user),method: :delete,:class => "dropdown-item",data: {confirm: "Are you sure?"} %>
      <div class="dropdown-divider"></div>
      <%= link_to 'Sign out',destroy_user_session_path, method: :delete,:class => "dropdown-item" %>
    </div>
  </li>
  <li class="nav-item">
    <%= link_to 'IDE',online_ide_path,:class => "nav-link" %>
  </li>
  <% end %>
</ul>
</div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Major</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
  <%= render 'layouts/navigation' %>
  <div id="page-content">
  <div class = "container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
    <%= render 'layouts/footer' %>
  </body>

</html>